# -*- coding: utf-8 -*-
"""Desafio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEUZNpRnGlfHfb8LKdrHnNGEQtlXNHEV
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""##1. Análisis de facturación

Ingreso total por cada tienda
"""

tupla_facturacion = (1, float(tienda['Precio'].sum())), (2, float(tienda2['Precio'].sum())), (3, float(tienda3['Precio'].sum())), (4, float(tienda4['Precio'].sum()))
lista_facturacion = list(tupla_facturacion)

tiendas = [elemento[0] for elemento in lista_facturacion]
facturacion = [elemento[1] for elemento in lista_facturacion]

import matplotlib
from matplotlib import pyplot as plt

tiendas = [elemento[0] for elemento in lista_facturacion]
facturacion = [elemento[1] for elemento in lista_facturacion]

plt.bar(x= tiendas, height=facturacion)
plt.xlabel('TIENDA')
plt.ylabel('FACTURACION')
plt.title('ANALISIS DE FACTURACION')
plt.grid()
plt.show()
plt.close('all')

"""#2. Ventas por categoría

En este debes calcular la cantidad de productos vendidos por categoría en cada tienda. La idea es agrupar los datos por categoría y contar el número de ventas de cada tipo, mostrando las categorías más populares de cada tienda.
"""

lista_categoria1 = (1, tienda.groupby('Categoría del Producto').sum()['Precio'])
tienda11 = lista_categoria1[0]
tienda12 = lista_categoria1[1].index.tolist()
tienda13 = lista_categoria1[1].tolist()

lista_categoria2 = (2, tienda2.groupby('Categoría del Producto').sum()['Precio'])
tienda21 = lista_categoria2[0]
tienda22 = lista_categoria2[1].index.tolist()
tienda23 = lista_categoria2[1].tolist()

lista_categoria3 = (3, tienda3.groupby('Categoría del Producto').sum()['Precio'])
tienda31 = lista_categoria3[0]
tienda32 = lista_categoria3[1].index.tolist()
tienda33 = lista_categoria3[1].tolist()

lista_categoria4 = (4, tienda4.groupby('Categoría del Producto').sum()['Precio'])
tienda41 = lista_categoria4[0]
tienda42 = lista_categoria4[1].index.tolist()
tienda43 = lista_categoria4[1].tolist()

max1_categoria = ''
max1_valor = 0
for indice in range(0, len(tienda13)):
    if tienda13[indice] > max1_valor:
        max1_categoria = tienda12[indice]
        max1_valor = tienda13[indice]

max2_categoria = ''
max2_valor = 0
for indice in range(0, len(tienda23)):
    if tienda23[indice] > max2_valor:
        max2_categoria = tienda22[indice]
        max2_valor = tienda23[indice]

max3_categoria = ''
max3_valor = 0
for indice in range(0, len(tienda33)):
    if tienda33[indice] > max3_valor:
        max3_categoria = tienda32[indice]
        max3_valor = tienda33[indice]

max4_categoria = ''
max4_valor = 0
for indice in range(0, len(tienda43)):
    if tienda43[indice] > max4_valor:
        max4_categoria = tienda42[indice]
        max4_valor = tienda43[indice]

print('Tienda = 1, Categoria = ', max1_categoria, ' Ventas = ', max1_valor)
print('Tienda = 2, Categoria = ', max2_categoria, ' Ventas = ', max2_valor)
print('Tienda = 3, Categoria = ', max3_categoria, ' Ventas = ', max3_valor)
print('Tienda = 4, Categoria = ', max4_categoria, ' Ventas = ', max4_valor)

"""#3. Calificación promedio de la tienda"""

suma1_calificacion = tienda['Calificación'].sum()
cuenta1_calificacion = tienda['Calificación'].count()
prom1_calificacion = round(float(suma1_calificacion / cuenta1_calificacion), 2)

suma2_calificacion = tienda2['Calificación'].sum()
cuenta2_calificacion = tienda2['Calificación'].count()
prom2_calificacion = round(float(suma2_calificacion / cuenta2_calificacion), 2)

suma3_calificacion = tienda3['Calificación'].sum()
cuenta3_calificacion = tienda3['Calificación'].count()
prom3_calificacion = round(float(suma3_calificacion / cuenta3_calificacion), 2)

suma4_calificacion = tienda4['Calificación'].sum()
cuenta4_calificacion = tienda4['Calificación'].count()
prom4_calificacion = round(float(suma4_calificacion / cuenta4_calificacion), 2)

print('Suma1 = ', suma1_calificacion, ' Cuenta1 = ', cuenta1_calificacion, 'Prom1 = ', prom1_calificacion)
print('Suma2 = ', suma2_calificacion, ' Cuenta2 = ', cuenta2_calificacion, 'Prom2 = ', prom2_calificacion)
print('Suma3 = ', suma3_calificacion, ' Cuenta3 = ', cuenta3_calificacion, 'Prom3 = ', prom3_calificacion)
print('Suma4 = ', suma4_calificacion, ' Cuenta4 = ', cuenta4_calificacion, 'Prom4 = ', prom4_calificacion)

"""#Productos más vendidos y menos vendidos"""



lista_producto1 = (1, tienda.groupby('Producto').sum()['Precio'])
venta11 = lista_producto1[0]
venta12 = lista_producto1[1].index.tolist()
venta13 = lista_producto1[1].tolist()

lista_producto2 = (1, tienda2.groupby('Producto').sum()['Precio'])
venta21 = lista_producto2[0]
venta22 = lista_producto2[1].index.tolist()
venta23 = lista_producto2[1].tolist()

lista_producto3 = (1, tienda.groupby('Producto').sum()['Precio'])
venta31 = lista_producto3[0]
venta32 = lista_producto3[1].index.tolist()
venta33 = lista_producto3[1].tolist()

lista_producto4 = (1, tienda.groupby('Producto').sum()['Precio'])
venta41 = lista_producto4[0]
venta42 = lista_producto4[1].index.tolist()
venta43 = lista_producto4[1].tolist()

max1_producto = ''
max1_venta = 0
for indice in range(0, len(venta13)):
    if venta13[indice] > max1_venta:
        max1_producto = venta12[indice]
        max1_venta = venta13[indice]

max2_producto = ''
max2_venta = 0
for indice in range(0, len(venta23)):
    if venta23[indice] > max2_venta:
        max2_producto = venta22[indice]
        max2_venta = venta23[indice]

max3_producto = ''
max3_venta = 0
for indice in range(0, len(venta33)):
    if venta33[indice] > max3_venta:
        max3_producto = venta32[indice]
        max3_venta = venta33[indice]

max4_producto = ''
max4_venta = 0
for indice in range(0, len(venta43)):
    if venta43[indice] > max4_venta:
        max4_producto = venta42[indice]
        max4_venta = venta43[indice]

min1_producto = ''
min1_venta = 100000000
for indice in range(0, len(venta13)):
    if venta13[indice] < min1_venta:
        min1_producto = venta12[indice]
        min1_venta = venta13[indice]

min2_producto = ''
min2_venta = 100000000
for indice in range(0, len(venta23)):
    if venta23[indice] < min2_venta:
        min2_producto = venta22[indice]
        min2_venta = venta23[indice]

min3_producto = ''
min3_venta = 100000000
for indice in range(0, len(venta33)):
    if venta33[indice] < min3_venta:
        min3_producto = venta32[indice]
        min3_venta = venta33[indice]

min4_producto = ''
min4_venta = 100000000
for indice in range(0, len(venta43)):
    if venta43[indice] < min4_venta:
        min4_producto = venta42[indice]
        min4_venta = venta43[indice]

print('Máximos:')
print('Tienda = 1, Producto = ', max1_producto, ' Ventas = ', max1_venta)
print('Tienda = 2, Producto = ', max2_producto, ' Ventas = ', max2_venta)
print('Tienda = 3, Producto = ', max3_producto, ' Ventas = ', max3_venta)
print('Tienda = 4, Producto = ', max4_producto, ' Ventas = ', max4_venta)

print('Mínimos:')
print('Tienda = 1, Producto = ', min1_producto, ' Ventas = ', min1_venta)
print('Tienda = 2, Producto = ', min2_producto, ' Ventas = ', min2_venta)
print('Tienda = 3, Producto = ', min3_producto, ' Ventas = ', min3_venta)
print('Tienda = 4, Producto = ', min4_producto, ' Ventas = ', min4_venta)

"""#Envío promedio por tienda"""

suma1_envio = tienda['Costo de envío'].sum()
cuenta1_envio = tienda['Costo de envío'].count()
prom1_envio = round(float(suma1_envio / cuenta1_envio), 2)

suma2_envio = tienda2['Costo de envío'].sum()
cuenta2_envio = tienda2['Costo de envío'].count()
prom2_envio = round(float(suma2_envio / cuenta2_envio), 2)

suma3_envio = tienda3['Costo de envío'].sum()
cuenta3_envio = tienda3['Costo de envío'].count()
prom3_envio = round(float(suma3_envio / cuenta3_envio), 2)

suma4_envio = tienda4['Costo de envío'].sum()
cuenta4_envio = tienda4['Costo de envío'].count()
prom4_envio = round(float(suma4_envio / cuenta4_envio), 2)

print('Suma1 = ', suma1_envio, ' Cuenta1 = ', cuenta1_envio, 'Prom1 = ', prom1_envio)
print('Suma2 = ', suma2_envio, ' Cuenta2 = ', cuenta2_envio, 'Prom2 = ', prom2_envio)
print('Suma3 = ', suma3_envio, ' Cuenta3 = ', cuenta3_envio, 'Prom3 = ', prom3_envio)
print('Suma4 = ', suma4_envio, ' Cuenta4 = ', cuenta4_envio, 'Prom4 = ', prom4_envio)

"""#DESAFIO"""

lista_lat1 = (tienda['lat'])
lista_lon1 = (tienda['lon'])
lista_lat2 = (tienda2['lat'])
lista_lon2 = (tienda2['lon'])
lista_lat3 = (tienda3['lat'])
lista_lon3 = (tienda3['lon'])
lista_lat4 = (tienda4['lat'])
lista_lon4 = (tienda4['lon'])

import matplotlib.pyplot as plt
import numpy as np

x1 = np.array(lista_lat1)
y1 = np.array(lista_lon1)
plt.scatter(x1, y1, color='blue')
plt.xlabel('Longitud')
plt.ylabel('Latitud')
plt.title('TIENDA 1')
plt.show()
plt.close('all')

x2 = np.array(lista_lat2)
y2 = np.array(lista_lon2)
plt.scatter(x2, y2, color='red')
plt.xlabel('Longitud')
plt.ylabel('Latitud')
plt.title('TIENDA 2')
plt.show()
plt.close('all')

x3 = np.array(lista_lat3)
y3 = np.array(lista_lon3)
plt.scatter(x3, y3, color='orange')
plt.xlabel('Longitud')
plt.ylabel('Latitud')
plt.title('TIENDA 3')
plt.show()
plt.close('all')

x4 = np.array(lista_lat4)
y4 = np.array(lista_lon4)
plt.scatter(x4, y4, color='green')
plt.xlabel('Longitud')
plt.ylabel('Latitud')
plt.title('TIENDA 4')
plt.show()
plt.close('all')

"""INFORME FINAL

Primer Desafío

Durante este desafío, ayudaremos al Sr. Juan a decidir qué tienda de su cadena Alura Store debe vender para iniciar un nuevo emprendimiento. Para ello, analizamos datos de ventas, rendimiento y reseñas de las 4 tiendas de Alura Store. El objetivo es identificar la tienda menos eficiente y presentar una recomendación final basada en los datos.

Para preparar esta recomendación, hice lo siguiente:

Cargar y manipular datos CSV con la biblioteca Pandas.
Crear visualizaciones de datos con la biblioteca Matplotlib.
Analizar métricas como ingresos, reseñas y rendimiento de ventas.
Los pasos que realicé fueron los siguientes:

Analizar datos de la tienda: evaluando información como los ingresos, las categorías más vendidas, las reseñas de los clientes, los productos más vendidos y el envío promedio.
Crear gráficos para visualización: decidí qué tipos de gráficos utilizar para presentar los resultados de forma clara y visual. Mínimo tres gráficos diferentes, que pueden incluir gráficos de barras, circulares, de dispersión y otros.
Para preparar la recomendación requerida, tuve en consideración que las cuatro tiendas presentan resultados bastante similares en cuanto a ventas totales y por categoría de producto para cada trimestre y año, lo mismo para los envíos totales (lo que se cobra al cliente comprador para enviarlo los productos a su casa), y las calificaciones de los clientes. Además, que de las ocho categorías de productos, cuatro de ellas explican poco más del 92% de las ventas totales: "Electrónicos", "Electrodomésticos", "Muebles" e "Instrumentos musicales".

Por lo tanto, para decidir qué recomendar al Sr. Juan, utilicé los siguientes factores:

Ventas anuales totales y ventas anuales para las cuatro categorías antes señaladoa.
Envíos anuales totales y envíos anuales para las cuatro categorías antes señaladas.
Promedio de las calificaciones de los clientes para todas las ventas, y para las ventas de las cuatro categorías de productos antes señaladas.
A continuación se presentan los gráficos asociados a los totales anuales.

Teniendo en consideración lo antes mencionado, y analizado la información disponible, mi recomendación es vender la tienda número 4.

Aprovecho de agradecer la oportunidad de responder a este desafío, resultando ser una excelente forma de ejercitar los conceptos aprendidos.
"""

ventas11 = tienda['Categoría del Producto']
ventas12 = tienda['Precio']
ventas13 = tienda['Costo de envío']
ventas14 = tienda['Calificación']
ventas15 = pd.to_datetime(tienda['Fecha de Compra'], dayfirst=True).dt.strftime('%Y')
suma1_precio = tienda['Precio'].groupby(ventas15).sum()/1000000
suma1_envio = tienda['Costo de envío'].groupby(ventas15).sum()/1000000
cuenta1_califica = tienda['Calificación'].groupby(ventas15).count()
prom1_califica = (tienda['Calificación'].groupby(ventas15).sum())/(tienda['Calificación'].groupby(ventas15).count())

ventas21 = tienda2['Categoría del Producto']
ventas22 = tienda2['Precio']
ventas23 = tienda2['Costo de envío']
ventas24 = tienda2['Calificación']
ventas25 = pd.to_datetime(tienda2['Fecha de Compra'], dayfirst=True).dt.strftime('%Y')
suma2_precio = tienda2['Precio'].groupby(ventas25).sum()/1000000
suma2_envio = tienda2['Costo de envío'].groupby(ventas25).sum()/1000000
cuenta2_califica = tienda2['Calificación'].groupby(ventas25).count()
prom2_califica = (tienda2['Calificación'].groupby(ventas25).sum())/(tienda2['Calificación'].groupby(ventas25).count())

ventas31 = tienda3['Categoría del Producto']
ventas32 = tienda3['Precio']
ventas33 = tienda3['Costo de envío']
ventas34 = tienda3['Calificación']
ventas35 = pd.to_datetime(tienda3['Fecha de Compra'], dayfirst=True).dt.strftime('%Y')
suma3_precio = tienda3['Precio'].groupby(ventas35).sum()/1000000
suma3_envio = tienda3['Costo de envío'].groupby(ventas35).sum()/1000000
cuenta3_califica = tienda3['Calificación'].groupby(ventas35).count()
prom3_califica = (tienda3['Calificación'].groupby(ventas35).sum())/(tienda3['Calificación'].groupby(ventas35).count())

ventas41 = tienda4['Categoría del Producto']
ventas42 = tienda4['Precio']
ventas43 = tienda4['Costo de envío']
ventas44 = tienda4['Calificación']
ventas45 = pd.to_datetime(tienda4['Fecha de Compra'], dayfirst=True).dt.strftime('%Y')
suma4_precio = tienda4['Precio'].groupby(ventas45).sum()/1000000
suma4_envio = tienda4['Costo de envío'].groupby(ventas45).sum()/1000000
cuenta4_califica = tienda4['Calificación'].groupby(ventas45).count()
prom4_califica = (tienda4['Calificación'].groupby(ventas45).sum())/(tienda4['Calificación'].groupby(ventas45).count())

import matplotlib.pyplot as plt
import numpy as np

x1 = suma1_precio.index.tolist()
y1 = suma1_precio.tolist()
x2 = suma2_precio.index.tolist()
y2 = suma2_precio.tolist()
x3 = suma3_precio.index.tolist()
y3 = suma3_precio.tolist()
x4 = suma4_precio.index.tolist()
y4 = suma4_precio.tolist()

w, x = 0.2, np.arange(len(x1))

fig, ax = plt.subplots()
ax.bar(x - 3*w/4, y1, width=w, label='Tienda 1')
ax.bar(x - w/4, y2, width=w, label='Tienda 2')
ax.bar(x + w/4, y3, width=w, label='Tienda 3')
ax.bar(x + 3*w/4, y4, width=w, label='Tienda 4')

ax.set_xticks(x)
ax.set_xticklabels(x1)
ax.set_ylabel('Ventas / 10e6')
ax.set_title('Ventas anuales por Tienda')
ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1 = suma1_envio.index.tolist()
y1 = suma1_envio.tolist()
x2 = suma2_envio.index.tolist()
y2 = suma2_envio.tolist()
x3 = suma3_envio.index.tolist()
y3 = suma3_envio.tolist()
x4 = suma4_envio.index.tolist()
y4 = suma4_envio.tolist()

w, x = 0.2, np.arange(len(x1))

fig, ax = plt.subplots()
ax.bar(x - 3*w/4, y1, width=w, label='Tienda 1')
ax.bar(x - w/4, y2, width=w, label='Tienda 2')
ax.bar(x + w/4, y3, width=w, label='Tienda 3')
ax.bar(x + 3*w/4, y4, width=w, label='Tienda 4')

ax.set_xticks(x)
ax.set_xticklabels(x1)
ax.set_ylabel('Envíos / 10e6')
ax.set_title('Envíos anuales por Tienda')
ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1 = prom1_califica.index.tolist()
y1 = prom1_califica.tolist()
x2 = prom2_califica.index.tolist()
y2 = prom2_califica.tolist()
x3 = prom3_califica.index.tolist()
y3 = prom3_califica.tolist()
x4 = prom4_califica.index.tolist()
y4 = prom4_califica.tolist()

w, x = 0.2, np.arange(len(x1))

fig, ax = plt.subplots()
ax.bar(x - 3*w/4, y1, width=w, label='Tienda 1')
ax.bar(x - w/4, y2, width=w, label='Tienda 2')
ax.bar(x + w/4, y3, width=w, label='Tienda 3')
ax.bar(x + 3*w/4, y4, width=w, label='Tienda 4')

ax.set_xticks(x)
ax.set_xticklabels(x1)
ax.set_ylabel('Calificaciones')
ax.set_title('Calificaciones anuales por Tienda')
ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()